from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
from datetime import datetime

class ChatRequest(BaseModel):
    query: str = Field(..., description="The user's query or instruction.")
    user_id: str = Field(..., description="The ID of the user making the request.")

class ChatResponse(BaseModel):
    response: str = Field(..., description="The final response generated by the agent.")
    tools_used: List[str] = Field(default_factory=list, description="List of tools invoked during the process.")

class DocumentUpload(BaseModel):
    title: str = Field(..., description="The title of the document.")
    content: str = Field(..., description="The text content of the document.")
    category: str = Field(..., description="Category (e.g., policy, handbook).")

class ActionRequest(BaseModel):
    user_id: str = Field(..., description="The ID of the user.")
    action: str = Field(..., description="The specific ERP action to execute.")
    payload: Dict[str, Any] = Field(default_factory=dict, description="Action parameters.")

class AuditLogSchema(BaseModel):
    id: int
    user_id: str
    request_intent: Optional[str] = None
    tools_called: Optional[List[str]] = None
    payload_used: Optional[Dict[str, Any]] = None
    result_returned: Optional[Dict[str, Any]] = None
    timestamp: datetime
    status: str

    class Config:
        from_attributes = True


class ERPNextPullSyncRequest(BaseModel):
    doctypes: Optional[List[str]] = Field(
        default=None,
        description="Optional list of ERPNext DocTypes to sync. Defaults to Employee, Attendance, Leave Application, Salary Slip.",
    )
    modified_after: Optional[str] = Field(
        default=None,
        description="Optional ISO timestamp override (e.g., 2026-04-20 10:00:00.000000). If omitted, checkpoints are used.",
    )
    limit_per_doctype: int = Field(default=200, ge=1, le=1000)


class ERPNextWebhookIngestResponse(BaseModel):
    event_id: int
    doctype: Optional[str] = None
    docname: Optional[str] = None
    event_type: Optional[str] = None
    signature_valid: bool
    sync_result: Optional[Dict[str, Any]] = None
