from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
from datetime import datetime

class ChatRequest(BaseModel):
    query: str = Field(..., description="The user's query or instruction.")
    user_id: str = Field(..., description="The ID of the user making the request.")

class ChatResponse(BaseModel):
    response: str = Field(..., description="The final response generated by the agent.")
    tools_used: List[str] = Field(default_factory=list, description="List of tools invoked during the process.")

class DocumentUpload(BaseModel):
    title: str = Field(..., description="The title of the document.")
    content: str = Field(..., description="The text content of the document.")
    category: str = Field(..., description="Category (e.g., policy, handbook).")

class ActionRequest(BaseModel):
    user_id: str = Field(..., description="The ID of the user.")
    action: str = Field(..., description="The specific ERP action to execute.")
    payload: Dict[str, Any] = Field(default_factory=dict, description="Action parameters.")

class AuditLogSchema(BaseModel):
    id: int
    user_id: str
    request_intent: Optional[str] = None
    tools_called: Optional[List[str]] = None
    payload_used: Optional[Dict[str, Any]] = None
    result_returned: Optional[Dict[str, Any]] = None
    timestamp: datetime
    status: str

    class Config:
        from_attributes = True
